variables:
  acrName: acrpvakscac1akzhol7
  aksClusterName: aks-pvaks-cac-001a
  azureResourceGroup: akzhols-rg-tfstate
  azureSubscriptionEndpoint: service-connection
  repository: akzholsweb

stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        pool: aks-private
        steps:
          - download: current
            artifact: $(repository)
            displayName: Download artifact

          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: "Replace tokens"
            inputs:
              rootDirectory: $(Pipeline.Workspace)\$(repository)
              targetFiles: |
                deployment.yml
              encoding: auto
              writeBOM: true
              escapeType: no escaping
              tokenPrefix: __
              tokenSuffix: __

          - task: Kubernetes@1
            displayName: "Apply Kubernetes Configuration"
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: apply
              useConfigurationFile: true
              configuration: $(Pipeline.Workspace)\$(repository)\deployment.yml
