variables:
  dockerHubServiceConnection: dockerHubConnection
  dockerHubRepository: suborov/myapp
  aksClusterName: aks-pvaks-cac-001a
  azureResourceGroup: rg-tfstate-akzhol
  azureSubscriptionEndpoint: service-connection


stages:
  - stage: Build
    jobs:
      - job: Build
        pool: aks-private
        steps:
          - task: Docker@2
            displayName: Build and Push Docker Image
            inputs:
              containerRegistry: $(dockerHubServiceConnection)
              repository: $(dockerHubRepository)
              command: buildAndPush
              Dockerfile: $(Build.Repository.LocalPath)/Dockerfile
              tags: |
                $(Build.BuildId)

          - task: CopyFiles@2
            inputs:
              sourceFolder: $(Build.Repository.LocalPath)
              contents: "deployment.yml"
              targetFolder: $(Build.ArtifactStagingDirectory)
              overwrite: true

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: $(dockerHubRepository)
  - stage: Deploy
    jobs:
      - job: Deploy
        pool: aks-private
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: $(dockerHubRepository)

          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: "Replace tokens"
            inputs:
              rootDirectory: $(Pipeline.Workspace)\$(repository)
              targetFiles: |
                deployment.yml
              encoding: auto
              writeBOM: true
              escapeType: no escaping
              tokenPrefix: __
              tokenSuffix: __

          - task: Kubernetes@1
            displayName: "kubectl"
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(aksClusterName)
              command: apply
              useConfigurationFile: true
              configuration: $(Pipeline.Workspace)\$(dockerHubRepository)\deployment.yml